### ISSUE TITLE
Help Needed: UWP App Crash on Personal Info Load - Dump Files Attached

### ISSUE THREAD

**Issue by joseraeiro** [passbolt/passbolt-windows#5]
Hello Passbolt community!

### Issue Description
I'm encountering a consistent crash in my UWP app, particularly when it tries to load personal account information. Despite extensive debugging efforts, the issue remains unresolved, and I am seeking assistance from the community.

- **Behavior**: The app crashes during the loading of personal account information.
- **Environment**: Windows 11 Pro, Version 22631, Architecture AMD64.

#### Steps to Reproduce first crash after installation
1. Start the app.
2. Go to the section for uploading the kit.
3. Upload it.
4. Wait for about 5 seconds.
5. Observe the crash.

#### Steps to Reproduce subsequent crashes
1. Start the app.
2. Wait for about 5 seconds.
3. Observe the crash

### What I've Tried
- Reviewing Event Viewer logs.
- Generating and analyzing full dump files.

### Attached Files
- [Event Viewer Logs](https://github.com/passbolt/passbolt-windows/files/13491491/Eventlog.txt)

- [Full Dump File](https://files.fm/u/p22h6bdaat)

### Request for Help
Any insights into the cause of this crash would be immensely helpful. Suggestions for further debugging or potential solutions are also welcome. If more information is needed, please let me know.

Thank you for your time and assistance!

**Comment by Gamabunta57** [comment]
Hey :wave: @joseraeiro!

This one is hard to know what's going on for me. I took a look on the Internet if somebody had similar issues and one solution could be to remove the app and "reinstall" it.

Basically, when you a UWP app, you should have the app appearing in your list of installed software from where you can remove it. So, yes, even if it's a Visual Studio built and launched app, Passbolt should appear in this list as well.

I have no idea, if it will work, but maybe you can try to remove it and then relaunch it from Visual Studio as you probably did.

Also, another thing I'm thinking about is that you might want to clean the account data also. For that you can find your Windows Credentials Manager and look for the installed credentials. You can clean it if there's something (be careful to clean only Passbolt related elements if any and not other apps data). 

Passbolt uses the following keys in your Credential Manager:
- account-metadata
- account-secret
- configuration

If you have accepted that the application access your information, these data should be associated with your username, otherwise the username should be empty.

**Comment by Gamabunta57** [comment]
Hello @joseraeiro!

I was wondering, do you have any news on that by any chance?
