### ISSUE TITLE
Download as .exe package

### ISSUE THREAD

**Issue by dbitsch-no** [passbolt/passbolt-windows#9]
Hello,

on my Windows machine the services/features AppX Package Installer and the microsoft Store are completely disabled and I'm unable to install Passbolt with the .misxbundle.

Is there any way you could deploy future versions also as executable .exe file?

**Comment by scadra** [comment]
@dbitsch-no,

First of all, I apologize for the issue you're experiencing. Do you think an MSIX package might work in your case?

If this is possible, you can download the bundle from [release 1.3.0](https://github.com/passbolt/passbolt-windows/releases/tag/v1.3.0)and change the extension from **msixbundle** to **zip**. Inside, you should find the MSIX package appropriate for your architecture.

Currently, we're unable to provide an EXE file due to the limitations of UWP technology. We can only support the new Windows format at the moment.

We understand that some users have faced similar issues and resolved them by running the following command:

`Add-AppxPackage -Path C:\Path\App-Package.msixbundle`

Could you please try this and let us know if it helps?

**Comment by dbitsch-no** [comment]
Hi scadra,

sorry for not updaing my answer. I actually was able to fix the problem and install the .msixbundle after all.

I had two missing services disabled, which are mandatory for opening .msixbundle:
- AppX Desktop Deployment
- Windows Store

After enabling those in "services.msc", the installation went through just fine.


Dennis

**Comment by scadra** [comment]
@dbitsch-no,

Thanks for your answer. Can you provide us more informations regarding your windows version and environment ? It can helps us to document it for the support team

**Comment by dbitsch-no** [comment]
Sure, I can try:

Back in the days I used to harden my windows installations by uninstalling/removing every AutoRun, Windows Service, Privacy Setting I could find.

- W10Privacy
- O&O AppBuster
- Win11Debloat (https://github.com/Raphire/Win11Debloat)

With O&O AppBuster I removed all System Apps that were not needed, including above mentioned AppX Desktop Deployment and Windows Store. 

The AppX Desktop Deployment package registers .msixbundle files and lets one execute them.
The Windows Store is needed after executing your .msixbundle file since it's the service that downloads the package files from the store.

Windows Store as well as Appx Desktop Deployment have be installed (as Windows package), and those also exist as a Windows Service which have to be running. (Run -> services.msc)

After that I was able to download/install your Passbolt client. 

Since there might be a lot of users out there that love to harden their system and especially disable the Windows Store, it might be good to offer us an additional way to install your client. Either as a simple .zip file or an ordinary .exe file.

**Comment by scadra** [comment]
Thanks for your reply @dbitsch-no,

Actually we are able to install the msixbundle without internet. When you say "Microsoft Store" do you want to say "Microsoft Store Install Service" which take care only for the installation of bundle ?

Regarding the EXE it is not possible with UWP tech, Teams has the same issue and they finally bootstrap the msixbundle into an exe, which is quite the same result in the end but useful for deployment engine.

Another solution can be to provide the MSIX according your architecture instead of the bundle ?

**Comment by dbitsch-no** [comment]
@scadra 

I just rechecked. The Microsoft Store is an AppX Package, in Powershell you can see the package with the command:

Get-AppxPackage -AllUsers -Name Microsoft.WindowsStore

This package was missing on my system due to the mentioned hardening measures. And without it I was unable to install the package.
